w5d1_homework/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create, :destroy]
  
end

w5d1_homework/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :session_token, :password_digest, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  after_initialize :ensure_session_token

  def reset_session_token!
    self.session_token = ensure_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
end

w5d1_homework/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in_user!(user)
    session[:session_token] = user.session_token
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

end

w5d1_homework/music_app/app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ['Invalid username/password']
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  # private
  #
  #  def user_params
  #    params.require(:user).permit(:email, :password)
  #  end


end

w5d1_homework/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(user_params)

    if user.save
      log_in_user!(user)
      redirect_to user_url(user)
    else
      user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
    render :show
  end

  private

   def user_params
     params.require(:user).permit(:email, :password)
   end

end

w5d1_homework/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def valid_authenticity
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'}>".html_safe
  end

end

w5d1_homework/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>MusicApp</h1>
    <% if current_user %>
      <%= current_user.email %>
      <%= button_to 'Logout', session_url(current_user), method: :delete%>
    <% end %>
    <%= yield %>
  </body>
</html>

w5d1_homework/music_app/app/views/session/new.html.erb
<h1>Log In</h1>

<form action="<%= session_index_url %>" method="post">
  <%= valid_authenticity %>

  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">
  <br>

  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">
  <br>

  <input type="submit" value="Login">

</form>

w5d1_homework/music_app/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
  <%= valid_authenticity %>

  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">
  <br>

  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">
  <br>

  <input type="submit" value="Create User">

</form>

w5d1_homework/music_app/app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>
Team Index Page